name: Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v2-beta
        with:
          node-version: 14.x

      - name: Install
        working-directory: ./generator
        run: npm install

      - name: Build
        working-directory: ./generator
        run: npm run build:release
        env:
          REPO_ACCESS_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}

      - name: Create Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dalmoori-font
          path: ./artifacts/

      - name: Set Comment Body
        id: get-comment-body
        run: |
          body=$(cat artifacts/advancement-report.md || echo Failed to generate Advancement Report)
          body="${body//'%'/'%25'}"
          body="${body//$'\n'/'%0A'}"
          body="${body//$'\r'/'%0D'}" 
          echo ::set-output name=body::$body
      - name: Comment Advancement
        uses: peter-evans/commit-comment@v1
        with:
          body: ${{ steps.get-comment-body.outputs.body }}
  release:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Evaluate tag status
        id: tag_status
        run: |
          latestTag=$(git rev-list --tags --max-count=1);
          latestCommit=$(git show -s --format=%H);
          echo ::set-output name=tagged::$([ "$latestTag" = "$latestCommit" ] && echo true || echo false);
          echo ::set-output name=name::$(git describe --tags);
      - name: Download artifact
        if: ${{ steps.tag_status.outputs.tagged == 'true' }}
        uses: actions/download-artifact@v2
        with:
          name: dalmoori-font
          path: ./dalmoori-font
      - name: Zipping Files
        if: ${{ steps.tag_status.outputs.tagged == 'true' }}
        run: zip -r -j dalmoori.zip dalmoori-font
      - name: Generate Changelog
        if: ${{ steps.tag_status.outputs.tagged == 'true' }}
        id: changelog
        uses: metcalfc/changelog-generator@v0.4.4
        with:
          myToken: ${{ secrets.GITHUB_TOKEN }}
      - name: Create Release
        if: ${{ steps.tag_status.outputs.tagged == 'true' }}
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag_status.outputs.name }}
          release_name: Release ${{ steps.tag_status.outputs.name }}
          body: ${{ steps.changelog.outputs.changelog }}
          draft: false
          prerelease: false
      - name: Upload Release Asset
        if: ${{ steps.tag_status.outputs.tagged == 'true' }}
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dalmoori.zip
          asset_name: dalmoori-font.zip
          asset_content_type: application/zip
      - name: Call Build Page
        uses: benc-uk/workflow-dispatch@v1
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          ref: page
          workflow: Build Page
