name: Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v2-beta
        with:
          node-version: 14.x

      - name: Install
        working-directory: ./scripts
        run: npm install

      - name: Build
        working-directory: ./scripts
        run: npm run build:release

      - name: Create Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dalmoori-font
          path: ./artifacts
        env: # Or as an environment variable
          ARTIFACT_DOWNLOAD_TOKEN: ${{ secrets.ARTIFACT_DOWNLOAD_TOKEN }}

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          enable_jekyll: true

      - name: Set Comment Body
        id: get-comment-body
        run: |
          body=$(cat artifacts/advancement-report.md || echo Failed to generate Advancement Report)
          echo ::set-output name=body::$body
      - name: Comment Advancement
        uses: peter-evans/commit-comment@v1
        with:
          body: ${{ steps.get-comment-body.outputs.body }}
